# Generated by Django 4.1.3 on 2023-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messenger',
            old_name='to_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='messenger',
            name='msg',
        ),
        migrations.AddField(
            model_name='messenger',
            name='message',
            field=models.TextField(default='', max_length=500),
        ),
    ]
