# Generated by Django 4.1.3 on 2023-07-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_rename_to_number_messenger_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messenger',
        ),
    ]
