# Generated by Django 4.1.3 on 2023-07-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
